# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Vibhu Verma
title: Principal Data Scientist
email: vvibhu1@gmail.com
website: https://github.com/vibhuverma17

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: vibhuvermaa
github_username:  vibhuverma17
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: vibhu-verma-017
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/dp.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, I'm Vibhu, a data scientist specializing in predictive modeling, XAI, and advanced AI/ML techniques to tackle complex business challenges. I have experience leveraging generative AI, anomaly detection, and network analysis to enhance decision-making, risk management, and operational efficiency. I'm skilled in deploying AI systems that drive automation, foster product innovation, and ensure fairness.

  I am most skilled in: <mark>AI/ML</mark>, <mark>XAI</mark> and <mark>Gen AI</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: MSBA Practicum - GWU
        link: github.com/vibhuverma17
        # link_text: Project Website
        description: | # this will include new lines to allow paragraphs
          During a Deloitte MSBA practicum, I worked as a data scientist in Washington, DC, from September to December 2020. I harmonized data from various sources, employed text mining and sentiment analysis to enhance data quality, and utilized machine learning techniques (XGBoost and logistic regression) to analyze factors influencing USAID's strategic resource allocation. I visualized the results in interactive Tableau dashboards, identifying patterns in regional and country-level investments to classify projects and assess their prosperity across 50+ countries.
          
          

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Capital One
        link: capitalone.com
        # link_text: capitalone.com
        sub_title: Principal Data Scientist
        caption: Jan 2022 - Present
        quote: >
          Solving 21st-century challenges by analyzing data and crafting groundbreaking innovations—like turning coffee into code and making spreadsheets as exciting as a rollercoaster ride!
        description: | # this will include new lines to allow paragraphs
            As a data-driven professional, I specialize in leveraging advanced analytical techniques to derive actionable insights from complex datasets. I have successfully implemented network analysis methodologies allowing for a deeper understanding of network dynamics. My experience includes designing and executing benchmarking algorithms using XGBoost, which effectively identify and address outlier subgroups. I also work with generative AI techniques for summarization, enhancing the ability to distill complex information into concise, actionable insights. My focus on employing innovative techniques has enabled organizations to enhance their decision-making processes and achieve strategic goals.
            
      - layout: left
        title: Kantar Consulting
        link: https://www.kantar.com/north-america
        # link_text: https://www.kantar.com/north-america
        sub_title: Data Analyst and Consultant
        caption: Jan 2021 - Jan 2022
        quote: >
          Turning retail chaos into profit gains like a magician pulling rabbits out of hats—except my tricks involve regression models, SQL sorcery, and automated segmentation! Who knew fetching data from FTP servers could feel like treasure hunting, and creating Power BI dashboards would make me the Picasso of profits?
        description: | # this will include new lines to allow paragraphs
             successfully improved revenue and profitability through the development of transferrable demand curves using ML models. This innovative approach allowed me to model the sales transfer between products within a retailer's assortment mix and suggest the optimal shelf configuration tailored to client needs. Additionally, I built robust ETL pipelines to efficiently fetch data from FTP servers and scripted various stored procedures in SQL to harmonize data for modeling baselines with time series techniques. This groundwork facilitated better planning for future promotions and accurate sales growth projections. Furthermore, I automated the private label segmentation process by utilizing customer decision trees through text mining and AutoML, enabling us to map various products to their financial data seamlessly. To further enhance our deliverables, I created interactive Power BI dashboards for clients, providing them with insightful visualizations that strengthen their decision-making capabilities.
            
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: George Washington University
        caption: 2019 - 2021
        sub_title: MS
        quote: >
          The George Washington University had its beginning in 1821 as The Columbian College in the District of Columbia.
        description: | # this will include new lines to allow paragraphs
          During my time at George Washington University, I earned a Master of Business Analytics (MSBA) with a focus on Data Science, with a key highlight being my practicum with Deloitte. I was also honored by the Golden Key International Honour Society, recognizing my academic excellence and leadership during my studies.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Camping/Traveling (Outdoors)
      - Photography
      - Geopolitics and History Nerd
    
      Look at this cool image I clicked in Alaska
      
      ![ALASKA](/images/F25858B6-1DB8-41D3-9ED4-C48FC6469A33_1_105_c.jpeg "GNP")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
