# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Vibhu Verma
title: Principal Data Scientist
email: vvibhu1@gmail.com
website: https://github.com/vibhuverma17

# Dark Mode (true/false/never)
darkmode: true

# Social links
twitter_username: vibhuvermaa
github_username:  vibhuverma17
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: vibhu-verma-017
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/dp.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, I'm Vibhu, a data scientist specializing in predictive modeling, XAI, and advanced AI/ML techniques to tackle complex business challenges. I have experience leveraging generative AI, anomaly detection, and network analysis to enhance decision-making, risk management, and operational efficiency. I'm skilled in deploying AI systems that drive automation, foster product innovation, and ensure fairness.

  I am most skilled in: <mark>AI/ML</mark>, <mark>XAI</mark> and <mark>Gen AI</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Super awesome project
        link: github.com/sproogen
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: The Boring Company
        link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Senior Network System Administrator
        caption: November 2017 - Present
        quote: >
          Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: George Washington University
        caption: 2019 - 2021
        sub_title: MS
        quote: >
          The George Washington University had its beginning in 1821 as The Columbian College in the District of Columbia.
        description: | # this will include new lines to allow paragraphs
          During my time at George Washington University, I earned a Master of Business Analytics (MSBA) with a focus on Data Science, with a key highlight being my practicum with Deloitte. I was also honored by the Golden Key International Honour Society, recognizing my academic excellence and leadership during my studies.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Camping/Traveling (Outdoors)
      - Photography
      - Geopolitics and History Nerd
    
      Look at this cool images I clicked 
      
      ![MONTANA](/images/7DA6AC3F-1DE2-427C-8FD7-1D48D8E509F0_1_105_c.jpeg "MONTANA")
      ![UTAH](/images/926A0787-0412-4D28-9311-5FFCDDEDA341_1_105_c.jpeg "UTAH")
      ![ALASKA](/images/F25858B6-1DB8-41D3-9ED4-C48FC6469A33_1_105_c.jpeg "GNP")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
